# Generated by Django 6.0.1 on 2026-02-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_post_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('portfolio', 'Portfolio'), ('business', 'Business'), ('ecommerce', 'E-commerce'), ('webapp', 'Web Application'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('ngo', 'NGO'), ('news', 'News'), ('social', 'Social'), ('search', 'Search Engine')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('features', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuiltItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='built_items/')),
                ('url', models.URLField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='built', to='portfolio_app.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Built',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
