# Generated by Django 6.0.1 on 2026-02-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='recaptcha_token',
        ),
    ]
