# Generated by Django 6.0.1 on 2026-02-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_remove_contactmessage_recaptcha_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_sent_at',
        ),
    ]
