# Generated by Django 5.2.7 on 2026-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_project_builtitem_delete_built_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='builtitem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='built_items/videos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='projects/videos/'),
        ),
    ]
